FROM python:3
#ENV TZ=Europe/London
#RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
COPY requirements.txt ./
#RUN apt-get update && apt-get install --no-cache --virtual .build-deps \
#    gcc \
#    python3-dev \
#    musl-dev \
#    postgresql-dev \
#    && pip install --no-cache-dir -r requirements.txt \
#    && apk del --no-cache .build-depsWORKDIR /usr/src/app
RUN pip install --no-cache-dir -r requirements.txt
COPY  . .
CMD [ "python", "./main.py" ]

