"""Add orders

Revision ID: 236e59b24b1c
Revises: d9155f37a04f
Create Date: 2020-01-26 18:04:47.362063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '236e59b24b1c'
down_revision = 'd9155f37a04f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_runner_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_book_id', sa.Integer(), nullable=False),
    sa.Column('market_runner_id', sa.Integer(), nullable=False),
    sa.Column('placed_date', sa.DateTime(), nullable=False),
    sa.Column('is_back', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('price_matched', sa.Float(), nullable=False),
    sa.Column('size_matched', sa.Float(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['market_book_id'], ['market_book.id'], ),
    sa.ForeignKeyConstraint(['market_runner_id'], ['market_runner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_runner_order_market_book_id'), 'market_runner_order', ['market_book_id'], unique=False)
    op.create_index(op.f('ix_market_runner_order_market_runner_id'), 'market_runner_order', ['market_runner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_runner_order_market_runner_id'), table_name='market_runner_order')
    op.drop_index(op.f('ix_market_runner_order_market_book_id'), table_name='market_runner_order')
    op.drop_table('market_runner_order')
    # ### end Alembic commands ###
