"""Fixup booleans in market book

Revision ID: 294bf6e51bf7
Revises: adfcef1a71d2
Create Date: 2019-11-13 16:42:28.876140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294bf6e51bf7'
down_revision = 'adfcef1a71d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_book', sa.Column('cross_matching', sa.Boolean(), nullable=True))
    op.add_column('market_book', sa.Column('inplay', sa.Boolean(), nullable=True))
    op.add_column('market_book', sa.Column('runners_voidable', sa.Boolean(), nullable=True))
    op.alter_column('market_book', 'bsp_reconciled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('market_book', 'complete',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('market_book', 'complete',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('market_book', 'bsp_reconciled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('market_book', 'runners_voidable')
    op.drop_column('market_book', 'inplay')
    op.drop_column('market_book', 'cross_matching')
    # ### end Alembic commands ###
