"""Remove order commission 2

Revision ID: 3bfc1f93128b
Revises: a7d4c24f1c0a
Create Date: 2020-01-28 20:18:39.037204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3bfc1f93128b'
down_revision = 'a7d4c24f1c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_runner_order', 'commission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_runner_order', sa.Column('commission', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
