"""Add market notes

Revision ID: 48e5cfc5a5c1
Revises: e3d63109ee6d
Create Date: 2020-02-04 21:25:38.017122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e5cfc5a5c1'
down_revision = 'e3d63109ee6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market', 'notes')
    # ### end Alembic commands ###
