"""Initial DB

Revision ID: 62b78c52be0c
Revises: 
Create Date: 2019-12-08 09:16:57.514737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62b78c52be0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('betfair_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('time_zone', sa.String(), nullable=False),
    sa.Column('venue', sa.String(), nullable=False),
    sa.Column('open_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('betfair_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runner_betfair_id'), 'runner', ['betfair_id'], unique=False)
    op.create_table('market',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('betfair_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('total_matched', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('delayed', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('bet_delay', sa.Integer(), nullable=False),
    sa.Column('bsp_reconciled', sa.Boolean(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('inplay', sa.Boolean(), nullable=False),
    sa.Column('number_of_winners', sa.Integer(), nullable=False),
    sa.Column('number_of_runners', sa.Integer(), nullable=False),
    sa.Column('number_of_active_runners', sa.Integer(), nullable=False),
    sa.Column('last_match_time', sa.DateTime(), nullable=True),
    sa.Column('total_matched', sa.Float(), nullable=False),
    sa.Column('total_available', sa.Float(), nullable=False),
    sa.Column('cross_matching', sa.Boolean(), nullable=False),
    sa.Column('runners_voidable', sa.Boolean(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['market.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_book_market_id'), 'market_book', ['market_id'], unique=False)
    op.create_table('market_runner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('runner_id', sa.Integer(), nullable=False),
    sa.Column('sort_priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['market.id'], ),
    sa.ForeignKeyConstraint(['runner_id'], ['runner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_runner_market_id'), 'market_runner', ['market_id'], unique=False)
    op.create_index(op.f('ix_market_runner_runner_id'), 'market_runner', ['runner_id'], unique=False)
    op.create_table('market_runner_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_book_id', sa.Integer(), nullable=False),
    sa.Column('market_runner_id', sa.Integer(), nullable=False),
    sa.Column('handicap', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('adjustment_factor', sa.Float(), nullable=False),
    sa.Column('last_price_traded', sa.Float(), nullable=True),
    sa.Column('total_matched', sa.Float(), nullable=True),
    sa.Column('removal_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['market_book_id'], ['market_book.id'], ),
    sa.ForeignKeyConstraint(['market_runner_id'], ['market_runner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_runner_book_market_book_id'), 'market_runner_book', ['market_book_id'], unique=False)
    op.create_index(op.f('ix_market_runner_book_market_runner_id'), 'market_runner_book', ['market_runner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_runner_book_market_runner_id'), table_name='market_runner_book')
    op.drop_index(op.f('ix_market_runner_book_market_book_id'), table_name='market_runner_book')
    op.drop_table('market_runner_book')
    op.drop_index(op.f('ix_market_runner_runner_id'), table_name='market_runner')
    op.drop_index(op.f('ix_market_runner_market_id'), table_name='market_runner')
    op.drop_table('market_runner')
    op.drop_index(op.f('ix_market_book_market_id'), table_name='market_book')
    op.drop_table('market_book')
    op.drop_table('market')
    op.drop_index(op.f('ix_runner_betfair_id'), table_name='runner')
    op.drop_table('runner')
    op.drop_table('event')
    # ### end Alembic commands ###
