"""Add jockey and trainer

Revision ID: 82a818e36e35
Revises: 208b659bd3c1
Create Date: 2020-03-14 09:28:07.166009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82a818e36e35'
down_revision = '208b659bd3c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jockey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('market_runner', sa.Column('jockey_id', sa.Integer(), nullable=True))
    op.add_column('market_runner', sa.Column('trainer_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_market_runner_jockey_id'), 'market_runner', ['jockey_id'], unique=False)
    op.create_index(op.f('ix_market_runner_trainer_id'), 'market_runner', ['trainer_id'], unique=False)
    op.create_foreign_key(None, 'market_runner', 'trainer', ['trainer_id'], ['id'])
    op.create_foreign_key(None, 'market_runner', 'jockey', ['jockey_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'market_runner', type_='foreignkey')
    op.drop_constraint(None, 'market_runner', type_='foreignkey')
    op.drop_index(op.f('ix_market_runner_trainer_id'), table_name='market_runner')
    op.drop_index(op.f('ix_market_runner_jockey_id'), table_name='market_runner')
    op.drop_column('market_runner', 'trainer_id')
    op.drop_column('market_runner', 'jockey_id')
    op.drop_table('trainer')
    op.drop_table('jockey')
    # ### end Alembic commands ###
