"""Makep booleans in market book non-null

Revision ID: 839866f16f27
Revises: 294bf6e51bf7
Create Date: 2019-11-13 17:05:16.482792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '839866f16f27'
down_revision = '294bf6e51bf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('market_book', 'cross_matching',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('market_book', 'inplay',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('market_book', 'runners_voidable',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('market_book', 'runners_voidable',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('market_book', 'inplay',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('market_book', 'cross_matching',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
