"""Add indexes

Revision ID: 8a65a42efb21
Revises: 839866f16f27
Create Date: 2019-12-05 09:55:42.404124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a65a42efb21'
down_revision = '839866f16f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_market_last_book_id'), 'market', ['last_book_id'], unique=False)
    op.create_index(op.f('ix_market_book_market_id'), 'market_book', ['market_id'], unique=False)
    op.create_index(op.f('ix_runner_betfair_id'), 'runner', ['betfair_id'], unique=False)
    op.create_index(op.f('ix_runner_market_id'), 'runner', ['market_id'], unique=False)
    op.create_index(op.f('ix_runner_book_market_book_id'), 'runner_book', ['market_book_id'], unique=False)
    op.create_index(op.f('ix_runner_book_runner_id'), 'runner_book', ['runner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runner_book_runner_id'), table_name='runner_book')
    op.drop_index(op.f('ix_runner_book_market_book_id'), table_name='runner_book')
    op.drop_index(op.f('ix_runner_market_id'), table_name='runner')
    op.drop_index(op.f('ix_runner_betfair_id'), table_name='runner')
    op.drop_index(op.f('ix_market_book_market_id'), table_name='market_book')
    op.drop_index(op.f('ix_market_last_book_id'), table_name='market')
    # ### end Alembic commands ###
