"""Add WOM 2

Revision ID: a550418a48e7
Revises: 47180caef6f4
Create Date: 2020-01-27 10:34:01.051140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a550418a48e7'
down_revision = '47180caef6f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_runner_book', sa.Column('wom_back', sa.Float(), nullable=True))
    op.add_column('market_runner_book', sa.Column('wom_lay', sa.Float(), nullable=True))
    op.add_column('market_runner_order', sa.Column('market_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_market_runner_order_market_id'), 'market_runner_order', ['market_id'], unique=False)
    op.drop_index('ix_market_runner_order_market_book_id', table_name='market_runner_order')
    op.drop_constraint('market_runner_order_market_book_id_fkey', 'market_runner_order', type_='foreignkey')
    op.create_foreign_key(None, 'market_runner_order', 'market', ['market_id'], ['id'])
    op.drop_column('market_runner_order', 'market_book_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_runner_order', sa.Column('market_book_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'market_runner_order', type_='foreignkey')
    op.create_foreign_key('market_runner_order_market_book_id_fkey', 'market_runner_order', 'market_book', ['market_book_id'], ['id'])
    op.create_index('ix_market_runner_order_market_book_id', 'market_runner_order', ['market_book_id'], unique=False)
    op.drop_index(op.f('ix_market_runner_order_market_id'), table_name='market_runner_order')
    op.drop_column('market_runner_order', 'market_id')
    op.drop_column('market_runner_book', 'wom_lay')
    op.drop_column('market_runner_book', 'wom_back')
    # ### end Alembic commands ###
