"""Remove order commission

Revision ID: a7d4c24f1c0a
Revises: b50c10a02e81
Create Date: 2020-01-28 20:00:13.437616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7d4c24f1c0a'
down_revision = 'b50c10a02e81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
