"""Add market last book reference

Revision ID: adfcef1a71d2
Revises: 2b4a8bf7b0bf
Create Date: 2019-11-13 09:27:06.333622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adfcef1a71d2'
down_revision = '2b4a8bf7b0bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market', sa.Column('last_book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'market', 'market_book', ['last_book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'market', type_='foreignkey')
    op.drop_column('market', 'last_book_id')
    # ### end Alembic commands ###
