"""Add Betfair order id

Revision ID: b50c10a02e81
Revises: fd0e69991cb7
Create Date: 2020-01-28 19:43:30.822402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50c10a02e81'
down_revision = 'fd0e69991cb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_runner_order', sa.Column('betfair_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_runner_order', 'betfair_id')
    # ### end Alembic commands ###
