"""Add last book references to market

Revision ID: d9155f37a04f
Revises: 62b78c52be0c
Create Date: 2019-12-08 09:28:56.817157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9155f37a04f'
down_revision = '62b78c52be0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market', sa.Column('last_book_id', sa.Integer(), nullable=True))
    op.add_column('market', sa.Column('last_inplay_book_id', sa.Integer(), nullable=True))
    op.add_column('market', sa.Column('last_prerace_book_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_market_last_book_id'), 'market', ['last_book_id'], unique=False)
    op.create_index(op.f('ix_market_last_inplay_book_id'), 'market', ['last_inplay_book_id'], unique=False)
    op.create_index(op.f('ix_market_last_prerace_book_id'), 'market', ['last_prerace_book_id'], unique=False)
    op.create_foreign_key(None, 'market', 'market_book', ['last_book_id'], ['id'])
    op.create_foreign_key(None, 'market', 'market_book', ['last_prerace_book_id'], ['id'])
    op.create_foreign_key(None, 'market', 'market_book', ['last_inplay_book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'market', type_='foreignkey')
    op.drop_constraint(None, 'market', type_='foreignkey')
    op.drop_constraint(None, 'market', type_='foreignkey')
    op.drop_index(op.f('ix_market_last_prerace_book_id'), table_name='market')
    op.drop_index(op.f('ix_market_last_inplay_book_id'), table_name='market')
    op.drop_index(op.f('ix_market_last_book_id'), table_name='market')
    op.drop_column('market', 'last_prerace_book_id')
    op.drop_column('market', 'last_inplay_book_id')
    op.drop_column('market', 'last_book_id')
    # ### end Alembic commands ###
