"""Update orders

Revision ID: fd0e69991cb7
Revises: a550418a48e7
Create Date: 2020-01-28 19:33:59.782078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd0e69991cb7'
down_revision = 'a550418a48e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_runner_order', sa.Column('commission', sa.Float(), nullable=False))
    op.add_column('market_runner_order', sa.Column('price_requested', sa.Float(), nullable=False))
    op.add_column('market_runner_order', sa.Column('side', sa.String(), nullable=False))
    op.drop_column('market_runner_order', 'size_matched')
    op.drop_column('market_runner_order', 'price')
    op.drop_column('market_runner_order', 'is_back')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_runner_order', sa.Column('is_back', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('market_runner_order', sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('market_runner_order', sa.Column('size_matched', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('market_runner_order', 'side')
    op.drop_column('market_runner_order', 'price_requested')
    op.drop_column('market_runner_order', 'commission')
    # ### end Alembic commands ###
